project:
  type: website
  output-dir: docs
website:
  title: "MLE - Fall 2024"
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: "#005A43"
    # foreground: "#A7DA92"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides.qmd  
      - mlesyllabus24.qmd
      - code.qmd

    tools:
      # - icon: twitter
        # href: https://twitter.com/clavedark
      - icon: github
        menu:
          - text: repo
            href:  https://github.com/clavedark/MLEfall24  

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    linkcolor: "#005A43"



